### PR TITLE
Add a "auto endianness" function for all listed formats with endianness variants.

### PR DESCRIPTION
**Pull request by JasonLG1979**

### CODE REVIEW

**Comment by JasonLG1979** [comment]
For the sake of completeness I can go though all of the formats with endianness variants and do the same, (create an auto endianness function) in this PR or a separate PR?

**Comment by JasonLG1979** [comment]
Another option is to add `NE` (native endianness) variants to the `Format` Enum that point to the proper endianness similar to what PulseAudio does. So for example a user could use `Format::S24NE` and always get the proper endianness.

**Comment by JasonLG1979** [comment]
I went a head and just added a convenience function for all listed formats with endianness variants. If that's not agreeable I can revert the commit.

**Comment by JasonLG1979** [comment]
When checking things with `clippy` I get:

```
warning: unknown lint: `clippy::suspicious`
  --> src/lib.rs:17:30
   |
17 | #![warn(clippy::correctness, clippy::suspicious, clippy::perf)]
   |                              ^^^^^^^^^^^^^^^^^^ help: did you mean: `clippy::suspicious_map`
   |
   = note: `#[warn(unknown_lints)]` on by default

warning: unknown lint: `clippy::suspicious`
  --> src/lib.rs:17:30
   |
17 | #![warn(clippy::correctness, clippy::suspicious, clippy::perf)]
   |                              ^^^^^^^^^^^^^^^^^^ help: did you mean: `clippy::suspicious_map`

warning: 2 warnings emitted
```

According to https://rust-lang.github.io/rust-clippy/master/ `clippy::suspicious` is not valid. There are however several that start with `suspicious`?

**Comment by diwic** [comment]
> According to https://rust-lang.github.io/rust-clippy/master/ clippy::suspicious is not valid.

It was recently added, maybe you have an old version of clippy? "Suspicious" is indeed a lint group on the page you link to.

**Comment by diwic** [comment]
Thanks for the patch, merged now :-)

**Comment by JasonLG1979** [comment]
> It was [recently added](https://github.com/rust-lang/rust-clippy/pull/7350), maybe you have an old version of clippy? "Suspicious" is indeed a lint group on the page you link to.

It must have not made to stable yet? I'm just ran `rustup update` and am on `rust version 1.53.0 (53cb7b09b 2021-06-17)` and still no dice, same message. Oh, well.

> Thanks for the patch, merged now :-)

Yep, I'm glad I could to even do just that little bit. You're certainly welcome. Thank you for the bindings. I've found them pretty useful and fun to play with.

**Pull request merged**
