### PR TITLE
mixer: add set_playback_volume_all

### PR DESCRIPTION
**Pull request by joerg-krause**

### CODE REVIEW

**Comment by diwic** [comment]
Looks good! Let me know if you need a release.

**Comment by joerg-krause** [comment]
Thanks for merging! A release would be nice, thanks!

**Comment by diwic** [comment]
Released v0.1.5. (Note: I messed up git history a bit so it might look like v0.1.4 contains your commit too, but it actually does not. You need 0.1.5.)

**Comment by joerg-krause** [comment]
Thanks!

**Pull request merged**
