### PR TITLE
Add DSD_U32_LE, DSD_U16_BE, DSD_U32_BE formats

### PR DESCRIPTION
**Pull request by danieljrmay**
Hello again! Here are the changes to `alsa-rs` which correspond to this 
[commit in `diwic/alsa-sys`](https://github.com/diwic/alsa-sys/commit/0e1b6eac6234776631a5ff1fc5ba81ec40b65661).

Thanks once more for all your work on these libraries — I really appreciate it! :grinning:

### CODE REVIEW

**Comment by danieljrmay** [comment]
Oh, I should have said that you would need to: 
1. Create an updated release of the `alsa-sys` crate.
2. And update the `alsa-sys` dependency version number in `alsa-rs`'s `Cargo.toml` before this merge request is accepted because otherwise it will break the build! :worried:

**Comment by diwic** [comment]
Hi,

I just released alsa-sys 0.2.1 with your commit in it. Could you squash your commits into one and make it refer to alsa-sys 0.2.1 before I merge it? Thanks!

**Comment by danieljrmay** [comment]
> Hi,
> 
> I just released alsa-sys 0.2.1 with your commit in it. Could you squash your commits into one and make it refer to alsa-sys 0.2.1 before I merge it? Thanks!

Will do!

**Comment by danieljrmay** [comment]
> I just released alsa-sys 0.2.1 with your commit in it. Could you squash your commits into one and make it refer to alsa-sys 0.2.1 before I merge it? Thanks!

So I think that's done now. Let me know if there is anything else I can do to help.

Cheers, Dan

**Comment by diwic** [comment]
Glad you're enjoying the crate!

 > Let me know if there is anything else I can do to help.

Well, if you like to contribute to the crate in general:
 * I know more examples and documentation is always appreciated by users
 * There are parts of the alsa-lib API that are still not covered
 * More unit tests help improve the quality of the library

**Comment by danieljrmay** [comment]
> Well, if you like to contribute to the crate in general:
> 
>     * I know more examples and documentation is always appreciated by users
>     * There are parts of the alsa-lib API that are still not covered
>     * More unit tests help improve the quality of the library

I will certainly give it a go. It would be a pleasure to give back!

**Pull request merged**
